{% set name = "freva-client" %}
{% set version = "2510.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/freva_client-{{ version }}.tar.gz
  sha256: dde26ffb6b36e3bc7b60d62a8b3d12b7fb602cd1e20f779b0bfe4d24a1a8b1d0

build:
  entry_points:
    - freva-client = freva_client:cli.app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2
    - appdirs
    - pip
  run:
    - python >={{ python_min }}
    - appdirs
    - pyyaml
    - requests
    - intake-esm
    - rich
    - setuptools
    - tomli
    - typer

test:
  imports:
    - freva_client
  commands:
    - pip check
    - freva-client --help
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Search for climate data based on key-value pairs
  dev_url: https://github.com/FREVA-CLINT/freva-nextgen/
  home: https://github.com/FREVA-CLINT/freva-nextgen
  description: |
    Freva (Free Evaluation System Framework) is a comprehensive platform
    designed to support researchers, especially in the atmospheric and climate
    science communities, in managing, searching, and analyzing large-scale
    datasets. It bridges the gap between data centers and user-defined tools,
    promoting efficient, reproducible, and collaborative research workflows.
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - antarcticrainforest
    - mo-dkrz
